### ISSUE TITLE
Is the new branch going to be buildable? 

### ISSUE THREAD

**Issue by albertpco** [howljs/react-native-calendar-kit#102]
Hey @howljs Thank you for all the work you are doing with this package. I have some components that may be of use such as the following. I did have a question on the new branch, will it be available to use soon? Trying to get the task/calendar app off the ground and it would be great to use the latest!
![Simulator Screen Shot - iPhone 14 Pro - 2023-07-28 at 17 03 38](https://github.com/howljs/react-native-calendar-kit/assets/116894437/f8a3879a-bf34-4577-8638-a7232334d2ac)

**Comment by howljs** [comment]
Version 2 still doesn’t have all the features of version 1 and it also lacks documentation. You will need to experiment with the examples from the develop branch to learn more about its features. Additionally, it hasn’t been thoroughly tested by me, and there may be issues on the Android side. I want to develop it quickly, but due to current time constraints, I am overwhelmed and won’t be able to support bug fixes or develop new features soon 😢

**Comment by albertpco** [comment]
No worries! I'd be happy to help. I'm focusing on just iOS anyways, so Android isn't a big concern atm.

**Comment by howljs** [comment]
Version 2.0.0 has been released, try it out with the new version.

Currently, there is no documentation for version 2.0.0, but I will update it in the next few days. In the meantime, you can follow the example code if you want to use the library early.
