### ISSUE TITLE
Blank header on Switching from Week to Day view at first mount of screen.

### ISSUE THREAD

**Issue by SwikarBhattarai** [howljs/react-native-calendar-kit#128]
https://github.com/user-attachments/assets/206c5e31-a88c-43cd-a4d1-13178e6cd682

At first mount of screen, the default number of days is 7 then  i switched to day view with number of days 1. The header becomes blank. @howljs

**Comment by howljs** [comment]
Switching between day and week views seems to be having performance issues. For now, you can use the method of separating the day calendar into a separate component.

Example:
```

viewMode === "day" ? <CalendarContainer>…</CalendarContainer> : <CalendarContainer>…</CalendarContainer>

```

**Comment by SwikarBhattarai** [comment]
Thanks, it works fine now .

**Comment by howljs** [comment]
I will notify you when I have fixed this issue. At that point, you can merge the code back into a single component.

**Comment by howljs** [comment]
ah. you can try change key of component. I’m a bit busy right now, I’ll send you the sample code later

**Comment by howljs** [comment]
@SwikarBhattarai Since the layout of the day mode is different from the week mode, there are some issues with switching between them. For now, you can handle it this way—changing the key, it will force refresh the calendar.

<img width="633" alt="Screenshot 2024-10-14 at 16 31 19" src="https://github.com/user-attachments/assets/4375c335-d873-4bb0-9f3f-9ec1a09e5d4b">
