### ISSUE TITLE
Hour and Header Customization

### ISSUE THREAD

**Issue by emrekazaz-hub** [howljs/react-native-calendar-kit#136]
I want to customize the hour and header day components. For the hours, I would like to add an icon next to the numbers (e.g., sun and moon icons) to indicate whether it's daytime or nighttime. For the header, I'd like to display some details about the day, including text and icons. Is this currently possible in V2, or is this feature something you plan to implement?
![howljsExample](https://github.com/user-attachments/assets/1be7e8dc-ba5d-457d-9b77-935869ce47c1)

**Comment by howljs** [comment]
With version 2.x, you can fully customize everything, but I forgot to export the renderDayBarItem function, so making this adjustment is a bit more laborious because you’ll have to modify the entire Header component using the renderHeaderItem function. I will add a custom day bar item function in the next version.

As per my plan, the new version will be released by the end of this week

**Comment by emrekazaz-hub** [comment]
And another question. When we use the numberOfDays for single day the header changes. The day header becomes prop of CalendarHeader (LeftAreaComponent). Is this feature or bug :)
![1 day view](https://github.com/user-attachments/assets/2ae6577b-7b6d-4a4e-b40f-a8773b124bfd)
![3 days view](https://github.com/user-attachments/assets/f5bfcb38-f95a-42b2-a329-342b147e1286)

**Comment by howljs** [comment]
The LeftAreaComponent is only supported in multi-day mode. For single-day mode, the left side will display the day item, while the right side will show all-day events, similar to Google Calendar

**Comment by howljs** [comment]
@emrekazaz-hub For the time being, renderDayItem has been added so you can customize each day. In the near future, I will break down the components further so that everyone can customize even more.

<img width="1098" alt="Screenshot 2024-10-21 at 20 43 27" src="https://github.com/user-attachments/assets/c29ddf7d-e0f0-43c5-8f31-4c3f8e20cea9">
