### ISSUE TITLE
onPressBackground doesn't work when we are in edit event mode.

### ISSUE THREAD

**Issue by SwikarBhattarai** [howljs/react-native-calendar-kit#17]
<img width="320" alt="Screen Shot 2022-12-07 at 2 43 03 PM" src="https://user-images.githubusercontent.com/36293831/206134006-62a023e9-fe8d-42e3-a39c-232552f0d6cd.png">

When we are in edit mode like above, how to return back to normal?

**Comment by howljs** [comment]
You can use your custom component and set selectedEvent to undefined
![Screenshot 2022-12-07 at 16 05 21](https://user-images.githubusercontent.com/33460888/206135718-68cdbbc4-6364-46ad-b5ec-e7ca1cd3ff37.png)

**Comment by howljs** [comment]
I enabled onPressBackground on v1.8.2. You can use like this
![Screenshot 2022-12-07 at 16 46 29](https://user-images.githubusercontent.com/33460888/206145003-97f1c651-e404-4546-bcbc-1a46c9e42580.png)

And i added **EditIndicatorComponent**. because I see on your UI it is skewed
<img width="138" alt="Screenshot 2022-12-07 at 16 51 51" src="https://user-images.githubusercontent.com/33460888/206146258-c40440c4-423d-4669-8e24-aa70bb2ed191.png">

![Screenshot 2022-12-07 at 16 50 05](https://user-images.githubusercontent.com/33460888/206145825-39ad9eae-68ee-4e8b-a5c2-3aa8376f495d.png)
![Screenshot 2022-12-07 at 16 49 59](https://user-images.githubusercontent.com/33460888/206145806-ad5148ed-a582-4ade-867c-631c2573581a.png)
