### ISSUE TITLE
Support for web?

### ISSUE THREAD

**Issue by dragonfire1119** [howljs/react-native-calendar-kit#20]
Are there plans to support react native web?

**Comment by hirvesh** [comment]
Any pointers @howljs

**Comment by krskrs** [comment]
Hi guys, what issues have you exactly encountered with web? 

Today I've been experimenting with it, in an EXPO project, and I'd like to confront my experience with yours.

In my case, I wasn't even able to open the app in browser after including this component, as I was getting some JS errors in browser console about unrecognized tokens in the build.

```Uncaught Error: Module parse failed: Unexpected token (97:84)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     zoom: props => {
|       var _timelineVerticalList;
>       let newHeight = (props === null || props === void 0 ? void 0 : props.height) ?? initialTimeIntervalHeight;
|       if (props !== null && props !== void 0 && props.scale) {
|         newHeight = timeIntervalHeight.value * props.scale;
    at ./node_modules/@howljs/calendar-kit/lib/module/components/Timeline/index.js (timeZone.js:2229:1)
```

After some research, I found out that there are those 'void 0' in the build sent to browser, which are causing the issue. This has been the first time I've encountered such issue in a react native component / library, and I'm not sure if it's caused by the way it has been built or something else (@howljs do you have any clues on this?)

However, I was able to circumvent the issue by adding the 'build' option below into the web section of Expo app.json config file. It seems to work, although I believe it would be better if the root cause was fixed, as the config flag I used seems even to be undocumented in the official Expo documentation.

```
    "web": {
      "build": {
        "babel": {
          "include": ["@howljs/calendar-kit"]
        }
      }
    }
```

**Comment by howljs** [comment]
Sorry. This library is not support react-native-web :(

**Comment by dtbaker** [comment]
is there any change to `react-native-web` support @howljs?  🙏 

I have tried it and it somewhat works, but I cannot get any of the drag/edit features working.
